- name: Copy file from remote to local
  hosts: 192.168.1.200
  tasks:
    - name: Copy file
      synchronize:
        src: /home/navya/Documents/virus.txt
        dest: /home/aviksha/Documents/virus.txt
        remote_src: yes
