- name: Copy file from remote to local
  hosts: 192.168.1.218
  tasks:
    - name: Copy file
      synchronize:
        src: /home/navya/Documents/virus.txt
        dest: /home/pooja/Documents/virus.txt
